### PR TITLE
Add Maven Central badge

### PR DESCRIPTION
**Pull request by szpak**
I'm not sure to which artifact should the link follows.

### CODE REVIEW

**Comment by pawelszymczyk** [comment]
Hi, please resolve conflicts

**Comment by adamdubiel** [comment]
Or it might be easier for us to just add this - don't bother with conflicts :) It's just a oneliner.

**Comment by szpak** [comment]
As I have always wanted to become a Hermes contributor I created rebased #151 ;-).

Btw, waiting over a month to merge a oneliner can generate conflicts.

**Comment by adamdubiel** [comment]
Yeah, we concentrate on refactors and coding too much maybe.. anyway - merged the other PR :)

**Pull request closed without merging**
