### PR TITLE
fixing latency timers on consumer and simplification of response hand…

### PR DESCRIPTION
**Pull request by rzukow**
…ling with one listener only but with async retry

### CODE REVIEW

**Comment by druminski** [comment]
:+1:

**Comment by pawelszymczyk** [comment]
:+1:

**Comment by pawelszymczyk** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/81)

**Comment by pawelszymczyk** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/81)

**Comment by pawelszymczyk** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/81)

**Comment by pawelszymczyk** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/81)

**Pull request merged**
