### PR TITLE
Allow to filter messages by any element in array (#1010)

### LINKED ISSUE #1010: Allow to filter messages by any element in array
It's impossible to filter avro messages by specific item in array. 

e.g. for message
```json
{
    "id": "0001",
    "topping": {
        "id": "5004",
        "type": "Maple",
        "description": "Maple syrup",
        "ingredients": ["corn syrup",  "water"]
    }
}
```
I would like to pass message when one of `topping.ingredients` item is `water`.

Of course, I could write filter like this
```json
{
  "type": "avropath",
  "path": ".topping.ingredients",
  "matcher": ".*water.*"
}
```
but also messages with `hot water` will pass because `topping.ingredients` array will be serialized to string: `[corn syrup,  water]`

My proposition is to extend filtering API with a new optional field (e.g. `matchingStrategy`) 
```json
{
  "type": "avropath",
  "path": ".topping.ingredients[*]",
  "matcher": ".*water.*",
  "matchingStrategy":  "all|any" //  "all" as default
}
```
Going further, `matchingType` should allow to change behaviour in stream processing in 
- `JsonPathPredicate` https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/json/JsonPathPredicate.java#L35 
- `AvroPathPredicate` https://github.com/allegro/hermes/blob/master/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/filtering/avro/AvroPathPredicate.java#L52

### PR DESCRIPTION
**Pull request by karolhor**
Resolves #1010

Checklist:
- [x] extend filters with matching strategy
- [x] unit tests
- [x] update documentation
- [x] apply changes in UI

### CODE REVIEW

**Comment by druminski** [comment]
@karolhor will you find time to finish this PR? can we help you somehow with it?

**Comment by karolhor** [comment]
@druminski right, this is quite old PR.

First of all, are you ok with my proposition of changes in issue #1010? I've suggested to add new field `matchingStrategy`

**Comment by druminski** [comment]
@karolhor we have read it just now and it looks fine for us :)

**Comment by karolhor** [comment]
@druminski I've finally updated docs and UI in my PR :) Below are the screenshots from my local `hermes-console`

filters1
filters2

**Pull request merged**
