### PR TITLE
Subscription metadata in console

### PR DESCRIPTION
**Pull request by dankraw**
Adds additional fields to "Edit subscription" modal.

metadata

### CODE REVIEW

**Comment by adamdubiel** [comment]
what about "normal" view? i see only the edit dialog changed

**Comment by dankraw** [comment]
@adamdubiel Right, I should add some info to the normal view. :)

**Comment by dankraw** [comment]
@adamdubiel added the metadata to the standard view:

normal-view

**Comment by adamdubiel** [comment]
👍

**Comment by druminski** [comment]
👍

**Pull request merged**
