### PR TITLE
#239 Fill #subscription in topic metrics

### PR DESCRIPTION
**Pull request by alberskib**

### CODE REVIEW

**Comment by adamdubiel** [comment]
I don't know if this counts as a metric we had in mind, any usecase maybe?

**Comment by alberskib** [comment]
To be honest I don't see any metric that would be reasonable fit into this field (int) - perhaps better option is to remove subscriptions, but (probably) it should go with new version of the API.

**Comment by adamdubiel** [comment]
Oh, wait, i didn't notice that this field was already in the model, just not used. I will dig around in the history to try to find what happened to it and then just merge the pull request :)

**Comment by alberskib** [comment]
Feel free to decline PR if you think that it is not good fit for this field :)

**Pull request merged**
