### PR TITLE
fixing #6 - wrong header is sent

### PR DESCRIPTION
**Pull request by adamdubiel**
[Review on Reviewable](https://reviewable.io/reviews/allegro/hermes/7)

### CODE REVIEW

**Comment by pawelszymczyk** [comment]
+1

**Comment by pjagielski** [comment]
Review status: 0 of 9 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/AbstractMessageSender.java, line 29 \[r2\]](https://reviewable.io:443/reviews/allegro/hermes/7#-Jpb_m_aN3QgxhBbiISH)** ([raw file](https://github.com/allegro/hermes/blob/43dcd9685cb6fbb97c10e955530531153c21a7cd/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/AbstractMessageSender.java#L29)):</sup>
do we indeed need this?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/7)

**Comment by pjagielski** [comment]
Review status: 0 of 9 files reviewed, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/7)

**Comment by pjagielski** [comment]
Review status: 0 of 9 files reviewed, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/7)

**Comment by druminski** [comment]
Review status: 0 of 9 files reviewed, all discussions resolved, all commit checks successful.

---

<sup>**[hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/AbstractMessageSender.java, line 29 \[r2\]](https://reviewable.io:443/reviews/allegro/hermes/7#-Jpb_m_aN3QgxhBbiISH)** ([raw file](https://github.com/allegro/hermes/blob/43dcd9685cb6fbb97c10e955530531153c21a7cd/hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/consumer/sender/AbstractMessageSender.java#L29)):</sup>
I think that we need to return some value in 'Hermes-Message-Id' header even if id of message is unavailable. Maybe "unavailable" will be fine (we could remove MessageId class). Message without id can occur when it's publish on a topic without using Hermes-frontend - it should be rare & worth of logging. What do think about that?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/7)

**Pull request closed without merging**
