### PR TITLE
Null check for cache event in BlacklistZookeeperNotifyingCache

### PR DESCRIPTION
**Pull request by chemicL**
Fixing https://github.com/allegro/hermes/issues/717

### CODE REVIEW

**Comment by adamdubiel** [comment]
`develop`, not master!

**Comment by chemicL** [comment]
Changed base to develop. Github should allow configuring this as the default ;-)

**Comment by adamdubiel** [comment]
Commit message is too vague, you changed specific cache not "null check for cache event"

**Comment by chemicL** [comment]
Updated the commit message

**Pull request merged**
