### PR TITLE
Issue #310 | HQL works with no java beans

### PR DESCRIPTION
**Pull request by druminski**

### CODE REVIEW

**Comment by wojtkiewicz** [comment]
:+1:

**Comment by jmnarloch** [comment]
By this ocassion there is one more thing that you could do in JsonQueryParser: https://github.com/allegro/hermes/blob/310_hql_with_no_java_beans/hermes-management/src/main/java/pl/allegro/tech/hermes/management/infrastructure/query/parser/json/JsonQueryParser.java#L72

is to branch to handle boolean values, something like: 

```
if(!node.isValueNode()) {
            throw new ParseException("The node value wasn't present");
        }
        if (node.isTextual()) {
            return node.asText();
        } else if (node.isBoolean()) {
            return node.asBoolean();
        } if (node.isInt()) {
            return node.asInt();
        } else if(node.isDouble()) {
            return node.asDouble();
        }
        return null;
```

Thanks

**Comment by druminski** [comment]
@jmnarloch good idea, done

**Comment by adamdubiel** [comment]
:+1:

**Pull request merged**
