### PR TITLE
removed offset monitoring

### PR DESCRIPTION
**Pull request by adamdubiel**
Removed offset lag monitor and fixed tracking query tests.

### CODE REVIEW

**Comment by druminski** [comment]
:+1:

**Comment by pawelszymczyk** [comment]
:+1:

**Comment by rzukow** [comment]
:+1:

**Comment by pawelszymczyk** [comment]
Reviewed 21 of 21 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/allegro/hermes/77)

**Pull request merged**
